apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: mindspore-job
spec:
  minAvailable: 1
  schedulerName: volcano
  policies:
    - event: PodEvicted
      action: RestartJob
  plugins:
    ssh: []
    env: []
    svc: []
  maxRetry: 5
  queue: default
  # Comment out the following section to enable volumes for job input/output.
  #volumes:
  #  - mountPath: "/myinput"
  #  - mountPath: "/myoutput"
  #    volumeClaimName: "testvolumeclaimname"
  #    volumeClaim:
  #      accessModes: [ "ReadWriteOnce" ]
  #      storageClassName: "my-storage-class"
  #      resources:
  #        requests:
  #          storage: 1Gi
  tasks:
    - replicas: 8
      name: "mindspore-test"
      template:
        spec:
          containers:
            - command: ["/bin/bash", "-c", "python /tmp/test/lenet.py"]
              image: mindspore/mindspore-cpu:0.2.0-alpha
              imagePullPolicy: IfNotPresent
              name: mindspore-job
              resources:
                limits:
                  cpu: "1"
                requests:
                  cpu: "1"
              volumeMounts:
              - name: training-result
                mountPath: /tmp/result
              - name: ms-mnist
                mountPath: /tmp/test
          restartPolicy: OnFailure
          volumes:
            - name: training-result
              emptyDir: {}
            - name: ms-mnist
              hostPath:
                path: /root/volcano/example/MindSpore-example/mindspore_cpu/
